defaults:
  - model:
      - qwen25_7b

megatron_training:
  model: qwen25_7b
  use_fused_rmsnorm: true
  use_mcore_models: true
  sequence_parallel: true
  use_flash_attn: true
  no_masked_softmax_fusion: true
  attention_softmax_in_fp32: true
  no_gradient_accumulation_fusion: true
  use_fused_swiglu: true
  use_fused_rotary_pos_emb: true
  bf16: true
  use_distributed_optimizer: true
  tokenizer_type: PretrainedFromHF
  tokenizer_name_or_path: /home/data/pae101/Qwen2.5-7B-Instruct
  global_batch_size: 4
  seq_length: 512
  save_interval: 10000
  train_iters: 1000
  stage: ray_grpo
  attention_dropout: 0.0
  init_method_std: 0.01
  hidden_dropout: 0.0
  distributed_backend: nccl
  no_shared_storage: true
  variable_seq_lengths: true
  norm_epsilon: 1e-6
  #  dataset_additional_keys: ['labels',]
  data_path: /workspace/MindSpeed-RL/dataset/pe-nlp/data
  split: 100,0,0

actor_config:
  model: qwen25_7b
  micro_batch_size: 1
  tensor_model_parallel_size: 4
  pipeline_model_parallel_size: 1
  lr: 1e-7
  lr_decay_style: constant
  min_lr: 0.0
  weight_decay: 0.0
  lr_warmup_fraction: 0.0
  clip_grad: 10000.0
  adam_beta1: 0.9
  adam_beta2: 0.999
  initial_loss_scale: 4096
  finetune: true
  load: /home/data/pae101/Qwen2.5-7B-Instruct_tp4pp1
  save: /home/data/pae101/Qwen2.5-7B-Instruct_tp4pp1/actor_ckpt
  no_load_optim: true
  no_load_rng: true

ref_config:
  model: qwen25_7b
  tensor_model_parallel_size: 2
  pipeline_model_parallel_size: 1
  micro_batch_size: 1
  load: /home/data/pae101/Qwen2.5-7B-Instruct_tp2pp1
  no_load_optim: true
  no_load_rng: true

reward_config:
  model: qwen25_7b
  tensor_model_parallel_size: 2
  pipeline_model_parallel_size: 1
  micro_batch_size: 1
  load: /home/data/pae101/Qwen2.5-7B-Instruct_tp2pp1
  no_load_optim: true
  no_load_rng: true

rl_config:
  blocking: false
  experience_count: 2
  gamma: 1.0
  lam: 0.95
  adv_estimator: group_norm
  kl_penalty: kl
  kl_ctrl_type: fixed
  init_kl_coef: 0.05
  mini_batch_size: 4
  max_prompt_length: 256
  epochs: 1
  clip_ratio: 0.2
  entropy_coeff: 0.001
  shuffle_mini_batch: false
  n_samples_per_prompt: 2
  rule_reward: false
  num_cpus_for_local_task: 1.0
  actor_resource:
    num_npus: 4
  reference_resource:
    num_npus: 2
  reward_resource:
    num_npus: 2

generate_config:
  # tokenizer相关配置
  micro_batch_size: 1
  trust_remote_code: true

  # 推理时的并行配置
  infer_tensor_parallel_size: 4
  infer_pipeline_parallel_size: 1
  infer_expert_parallel_size: 1

  # vllm 模型相关设置
  max_num_seqs: 16
  max_model_len: 4096
  dtype: "bfloat16"
  gpu_memory_utilization: 0.6

  offload_train_optimizer: true
  offload_train_grad: true
  offload_train_param: true

  # 采样配置
  sampling_config:
    logprobs: 1
    max_tokens: 256
    top_p: 0.9
    top_k: 50
    min_p: 0.01
    temperature: 0.9
    detokenize: false

